###########################
# zabbix-agent            #
###########################
FROM centos:7
RUN rpm -ivh http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm && \
  yum install -y zabbix-agent docker sudo && \ 
  yum clean all
ADD data /data
WORKDIR /data
VOLUME ["/var/run/docker.sock","/host/cgroup"]
CMD ["/data/start.sh"]
